### ISSUE TITLE
dsc_securityoption not behaving idempotently

### ISSUE THREAD

**Issue by bwilcox** [puppetlabs/ruby-pwsh#104]
## Describe the Bug
With the following resource defined:

```
  dsc_securityoption { 'Enforce Anonoymous SID Translation':
    dsc_name => 'Enforce Anonymous SID Translation',
    dsc_network_access_allow_anonymous_sid_name_translation => 'Disabled',
  }
```
The first puppet run says it's changing it, which is expected.  All subsequent puppet runs also say they are changing it.

```
PS C:\Users\Administrator\test\modules\networkingdsc> puppet apply .\examples\test.pp --modulepath .\spec\fixtures\modules\
Notice: Compiled catalog for lay-escalation.delivery.puppetlabs.net in environment production in 0.42 seconds
Notice: /Stage[main]/Main/Dsc_securityoption[Enforce Anonoymous SID Translation]/dsc_network_access_allow_anonymous_sid_name_translation: dsc_network_access_allow_anonymous_sid_name_translation changed  to 'Disabled'
Notice: dsc_securityoption[{:name=>"Enforce Anonoymous SID Translation", :dsc_name=>"Enforce Anonymous SID Translation"}]: Updating: Finished in 2.39 seconds
Notice: Applied catalog in 3.88 seconds
```

I thought this might be an instance where we need to add a runas credential to get it to work, but even adding a credential to the resource dosen't change the behavior.

## Expected Behavior
Expect the resource to change once and each puppet run after to not change it again.

## Steps to Reproduce
Add the resource to a manifest and run.

## Environment
 - pwshlib 0.7.3
 - securitypolicydsc (3.0.0-preview3)
 - Platform Windows 2019

## Additional Context
I attempted to pry into it and it looks to me like the comparison for 'is_same' in canonicalize came back as true.  So I would expect it to not make a change, yet it does.

**Comment by bwilcox** [comment]
I'm experiencing the same behavior with the dsc_userrightsassignment resource.  It looks like the changes aren't actually being made.

**Comment by michaeltlombardi** [comment]
I thought there was something goofy happening with SecurityOption that sounded familiar and, sure enough, it doesn't return the `Name` property either - I had put up a patch for the AccountPolicy but SecurityPolicy has the same issue.

I've put up a PR upstream to fix that at dsccommunity/SecurityPolicyDsc#159

If you can give me an example manifest using `dsc_userrightsassignment` I can take a look at that too - my testing leads me to think that the error in that case is actually a little different; I think there's a bit of an issue with one of the following:

- canonicalizing lists of users, _especially_ if you don't specify their fully qualified name (ie `foo` instead of `my_domain\foo`
- comparing non-forced lists of identities (ie if the state is `['foo', 'bar', 'baz']` and the only identity in the manifest is `foo`, it "looks like" a change to Puppet)

I'll have to do a bit of further investigation on that and see what I can turn up.

**Comment by bwilcox** [comment]
Here's a userrightsassignment example:

```
dsc_userrightsassignment{ 'Allow log on locally':
  dsc_identity => ['Builtin\Administrators'],
  dsc_policy => 'Allow_log_on_locally',
  dsc_force  => true,
  dsc_psdscrunascredential => {
    user => 'administrator',
    password => Sensitive('Qu@lity!'),
}
```

Note I added the force and run-as credential to see if that would change the result, they did not.  The resource does seem to actually change anything even though it says it does.

**Comment by michaeltlombardi** [comment]
@bwilcox I don't expect specifying the runas credential would make a difference, I do expect that `Force` would - did you confirm that force was being passed during the `set` invocation?

In my local testing it did add `foo` to the identity list, but unless I included the full list it would flap.

**Comment by bwilcox** [comment]
@michaeltlombardi I spun up another test box and now I can't get dsc_userrightsassignment to fail.  Go figure.  On my customers system, it still fails.  Naturally.  pwshlib is the same version, securitypolicydsc is the same version.  So I think my next move will be to copy the whole module and run the whole thing in my lab.  Not sure if I'll get to that this week, we'll see.

**Comment by bwilcox** [comment]
@michaeltlombardi I can't get the full module to fail in the lab the way it does at the customer's site.  So I think the userrightassignment issue is comming from somewhere else.  I think we can close this one based on the fix you've submitted for securitypolicydsc.

**Comment by michaeltlombardi** [comment]
Okay, that works for me! If you're able to put together a repro for `userrightsassignment`, we can open another issue or find some time to pair!
