### ISSUE TITLE
Thread issue when running in sidekiq

### ISSUE THREAD

**Issue by vddgil** [puppetlabs/ruby-pwsh#180]
## Describe the Bug
When running multiple scripts in parrallel in sidekiq, sometimes I get the following error:
`gems/ruby-pwsh-0.10.0/lib/pwsh.rb:563:in `sysread': stream closed in another thread (IOError)`

## Expected Behavior
Sidekiq thread should not share the same manager instance

Is there a way to avoid that?

**Comment by sanfrancrisko** [comment]
Hi @vddgil , thanks for reporting. 

We'll look in to this. In order to assist in a reproduction of the issue on our side, would you have a small snippet of the code where the `read_streams` method is being called? We can contrive that on our side, but it would be helpful if you have something that causes this issue already, it would be handy, especially if it's something to do with resource contention

**Comment by michaeltlombardi** [comment]
This has been fixed in #180 and will be included in the next release, at which time we will close this issue.

**Comment by michaeltlombardi** [comment]
[`0.10.1` has been released](https://github.com/puppetlabs/ruby-pwsh/tree/0.10.1) and should have fixed this!
